const template = `
### Commit Lint <COMMIT_LINT_STATUS>

<COMMIY_ERR_SUM>

<COMMITS_PLACEHOLDER>

You may need to [change the commit messages][ref] to comply with the \
repository [contributing guidelines][guidelines].

### WIP <WIP_STATUS>

<WIP_PLACEHOLDER>

--------

🐱 This comment was generated by [**tipe-cat-bot**][repo]. Please report \
issues [here][issues].

Happy coding!

[ref]: https://help.github.com/articles/changing-a-commit-message/
[repo]: https://github.com/tipeio/tipe-cat-bot
[issues]: https://github.com/tipeio/tipe-cat-bot/issues
[guidelines]: https://github.com/tipeio/tipe-conventions/blob/4987a13f29bc7e5fcbb428dd7b245fedcd5bf6ce/COMMIT_CONVENTION.md#git-commit-message-convention
`

function format(lintStatus, wipStatus) {
  let commitsMessage = ''

  lintStatus.report.commits.forEach(c => {
    commitsMessage += `* Commit: ${c.sha}\n`
    commitsMessage += c.errors.map(e => `  - ✖ ${e.message}\n`).join('')
    commitsMessage += c.warnings.map(w => `  - ⚠ ${w.message}\n`).join('')
  })

  return template
    .replace('<COMMIT_LINT_STATUS>', lintStatus.emojiStatus)
    .replace('<COMMIY_ERR_SUM>', lintStatus.errSum)
    .replace('<COMMITS_PLACEHOLDER>', commitsMessage)
    .replace('<WIP_PLACEHOLDER>', wipStatus.description)
    .replace('<WIP_STATUS>', wipStatus.emojiStatus)
}

module.exports = format
