const template = `
There were the following issues with this Pull Request

<PLACEHOLDER>

You may need to [change the commit messages][ref] to comply with the \
repository [contributing guidelines][guidelines].



--------

🐱 This comment was generated by [**tipe-cat-bot**][repo]. Please report \
issues [here][issues].

Happy coding!

[ref]: https://help.github.com/articles/changing-a-commit-message/
[repo]: https://github.com/tipeio/tipe-cat-bot
[issues]: https://github.com/tipeio/tipe-cat-bot/issues
[guidelines]: https://github.com/tipeio/tipe-conventions/blob/4987a13f29bc7e5fcbb428dd7b245fedcd5bf6ce/COMMIT_CONVENTION.md#git-commit-message-convention
`

function format(commits) {
  let message = ''

  commits.forEach(c => {
    message += `* Commit: ${c.sha}\n`
    message += c.errors.map(e => `  - ✖ ${e.message}\n`).join('')
    message += c.warnings.map(w => `  - ⚠ ${w.message}\n`).join('')
  })

  return template.replace('<PLACEHOLDER>', message)
}

module.exports = format
